### ISSUE TITLE
Training dataset used

### ISSUE THREAD

**Issue by Nerdyvedi** [JACKYLUO1991/Face-skin-hair-segmentaiton-and-skin-color-evaluation#3]
Thank you for sharing this wonderful work.

The paper mentions that the data is being acquired from 3 different sources:
1. LFW subset : 2927 Images, 1500 used for training
2. CelebA subset : 3556 Images, As in "A Deep Learning Approach to Hair Segmentation and Color 
    Extraction from Facial Images"
3. Figaro1k : Only those images which have faces are used, 171 Images

I could not understand how you used these datasets to train the model. Do you combine them to make one single set of training data, or do you train separate models? 
Sorry , if this is a silly question, I could not understand the training procedure from the paper.

Another question that I have is , Nowhere in this code I could find a face detector which would select images from Figaro1k which contain images.

Your help would mean a lot. Thanks

**Comment by JACKYLUO1991** [comment]
Thank you very much for your support. &nbsp;Let me explain the problem you raised:&nbsp;
1. Train three models on three different datasets;&nbsp;
2. The face detector can be chosen at will. In order to test fairness, it is recommended to choose Dlib;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Vedanta Jha"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月30日(星期四) 晚上9:01
收件人:&nbsp;"JACKYLUO1991/Face-skin-hair-segmentaiton-and-skin-color-evaluation"<Face-skin-hair-segmentaiton-and-skin-color-evaluation@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[JACKYLUO1991/Face-skin-hair-segmentaiton-and-skin-color-evaluation] Training dataset used (#3)




Thank you for sharing this wonderful work.
 
The paper mentions that the data is being acquired from 3 different sources:
  
LFW subset : 2927 Images, 1500 used for training
 
CelebA subset : 3556 Images, As in "A Deep Learning Approach to Hair Segmentation and Color
 Extraction from Facial Images"
 
Figaro1k : Only those images which have faces are used, 171 Images
  
I could not understand how you used these datasets to train the model. Do you combine them to make one single set of training data, or do you train separate models?
 Sorry , if this is a silly question, I could not understand the training procedure from the paper.
 
Another question that I have is , Nowhere in this code I could find a face detector which would select images from Figaro1k which contain images.
 
Your help would mean a lot. Thanks

**Comment by Nerdyvedi** [comment]
How do you split the Figaro and CelebA dataset, Like how many for training and how many for testing ?
And then do you use a separate model for training on CamVid dataset ? 

PS :  I am getting 183 images with faces on applying dlib to figarro1k, the paper mentions 171

**Comment by Nerdyvedi** [comment]
@JACKYLUO1991 , Could you please share how split the data for Figaro and CelebA as well ? Thank you

**Comment by JACKYLUO1991** [comment]
@Nerdyvedi You can see the comments I respond to others.

**Comment by Nerdyvedi** [comment]
Okay, Thanks
